Workflow results jobs

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -37,3 +37,20 @@ jobs:
     needs: [builds]
     secrets: inherit
     uses: ./.github/workflows/.deploy.yml
+
+  results:
+    name: PR Results
+    if: always()
+    # Include all needs that could have failures!
+    needs: [builds, deploys]
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          # View results
+          echo "needs.*.result: ${{ toJson(needs.*.result) }}"
+
+      - if: contains(needs.*.result, 'failure')
+        run: |
+          # Job failure found
+          echo "At least one job has failed"
+          exit 1
diff --git a/.github/workflows/pr-validate.yml b/.github/workflows/pr-validate.yml
--- a/.github/workflows/pr-validate.yml
+++ b/.github/workflows/pr-validate.yml
@@ -13,7 +13,7 @@ jobs:
     name: Initialize
     outputs:
       mod-tag: ${{ steps.mod-tag.outputs.mod-tag }}
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
     steps:
       - name: Get PR Number Mod 50
         id: mod-tag
@@ -30,8 +30,16 @@ jobs:
 
   results:
     name: Validate Results
-    if: always() && (!failure()) && (!cancelled())
+    if: always()
     needs: [validate]
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
     steps:
-      - run: echo "Success!"
+      - run: |
+          # View results
+          echo "needs.*.result: ${{ toJson(needs.*.result) }}"
+
+      - if: contains(needs.*.result, 'failure')
+        run: |
+          # Job failure found
+          echo "At least one job has failed"
+          exit 1
